-- Marina Kent
DROP DATABASE IF EXISTS GSC;

CREATE DATABASE GSC;
use GSC;

CREATE TABLE GirlScouts (
  gsid INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR (256) NOT NULL, 
  troop VARCHAR (256) NOT NULL
);

CREATE TABLE Customer (
  cid int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR (256) NOT NULL, 
  street VARCHAR (256) NOT NULL, 
  city VARCHAR (256) NOT NULL, 
  state VARCHAR (256) NOT NULL, 
  zip INT UNSIGNED NOT NULL
);

CREATE TABLE Orders (
  gsid INT UNSIGNED NOT NULL, 
  orderID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  cid INT UNSIGNED NOT NULL,
  FOREIGN KEY (cid) REFERENCES customer(cid),
  FOREIGN KEY (gsid) REFERENCES girlScouts(gsid)
);

CREATE TABLE Cookies (
  type VARCHAR (256) NOT NULL, 
  quantity INT SIGNED NOT NULL, 
  CookieOrderID INT UNSIGNED NOT NULL,
  FOREIGN KEY (CookieOrderID) REFERENCES Orders(orderID)
);
   